import { ADD_TASK, COMPLETE_TASK, REMOVE_TASK, SET_CURRENT_DAY} from "./actions";

const InitialState = {
    currentDay: {},
    tasks: [],
    month: {
        January: {
            1: { tasks: [] },
            2: { tasks: [] },
            3: { tasks: [] },
            4: { tasks: [] },
            5: { tasks: [] },
            6: { tasks: [] },
            7: { tasks: [] },
            8: { tasks: [] },
            9: { tasks: [] },
            10: { tasks: [] },
            11: { tasks: [] },
            12: { tasks: [] },
            13: { tasks: [] },
            14: { tasks: [] },
            15: { tasks: [] },
            16: { tasks: [] },
            17: { tasks: [] },
            18: { tasks: [] },
            19: { tasks: [] },
            20: { tasks: [] },
            21: { tasks: [] },
            22: { tasks: [] },
            23: { tasks: [] },
            24: { tasks: [] },
            25: { tasks: [] },
            26: { tasks: [] },
            27: { tasks: [] },
            28: { tasks: [] },
            29: { tasks: [] },
            30: { tasks: [] },
            31: { tasks: [] },
        },
        February: {
            1: { tasks: [] },
            2: { tasks: [] },
            3: { tasks: [] },
            4: { tasks: [] },
            5: { tasks: [] },
            6: { tasks: [] },
            7: { tasks: [] },
            8: { tasks: [] },
            9: { tasks: [] },
            10: { tasks: [] },
            11: { tasks: [] },
            12: { tasks: [] },
            13: { tasks: [] },
            14: { tasks: [] },
            15: { tasks: [] },
            16: { tasks: [] },
            17: { tasks: [] },
            18: { tasks: [] },
            19: { tasks: [] },
            20: { tasks: [] },
            21: { tasks: [] },
            22: { tasks: [] },
            23: { tasks: [] },
            24: { tasks: [] },
            25: { tasks: [] },
            26: { tasks: [] },
            27: { tasks: [] },
            28: { tasks: [] },
            29: { tasks: [] },
            30: { tasks: [] },
            31: { tasks: [] },
        },
        March: {
            1: { tasks: [] },
            2: { tasks: [] },
            3: { tasks: [] },
            4: { tasks: [] },
            5: { tasks: [] },
            6: { tasks: [] },
            7: { tasks: [] },
            8: { tasks: [] },
            9: { tasks: [] },
            10: { tasks: [] },
            11: { tasks: [] },
            12: { tasks: [] },
            13: { tasks: [] },
            14: { tasks: [] },
            15: { tasks: [] },
            16: { tasks: [] },
            17: { tasks: [] },
            18: { tasks: [] },
            19: { tasks: [] },
            20: { tasks: [] },
            21: { tasks: [] },
            22: { tasks: [] },
            23: { tasks: [] },
            24: { tasks: [] },
            25: { tasks: [] },
            26: { tasks: [] },
            27: { tasks: [] },
            28: { tasks: [] },
            29: { tasks: [] },
            30: { tasks: [] },
            31: { tasks: [] },
        },
        April: {
            1: { tasks: [] },
            2: { tasks: [] },
            3: { tasks: [] },
            4: { tasks: [] },
            5: { tasks: [] },
            6: { tasks: [] },
            7: { tasks: [] },
            8: { tasks: [] },
            9: { tasks: [] },
            10: { tasks: [] },
            11: { tasks: [] },
            12: { tasks: [] },
            13: { tasks: [] },
            14: { tasks: [] },
            15: { tasks: [] },
            16: { tasks: [] },
            17: { tasks: [] },
            18: { tasks: [] },
            19: { tasks: [] },
            20: { tasks: [] },
            21: { tasks: [] },
            22: { tasks: [] },
            23: { tasks: [] },
            24: { tasks: [] },
            25: { tasks: [] },
            26: { tasks: [] },
            27: { tasks: [] },
            28: { tasks: [] },
            29: { tasks: [] },
            30: { tasks: [] },
            31: { tasks: [] },
        },
        May: {
            1: { tasks: [] },
            2: { tasks: [] },
            3: { tasks: [] },
            4: { tasks: [] },
            5: { tasks: [] },
            6: { tasks: [] },
            7: { tasks: [] },
            8: { tasks: [] },
            9: { tasks: [] },
            10: { tasks: [] },
            11: { tasks: [] },
            12: { tasks: [] },
            13: { tasks: [] },
            14: { tasks: [] },
            15: { tasks: [] },
            16: { tasks: [] },
            17: { tasks: [] },
            18: { tasks: [] },
            19: { tasks: [] },
            20: { tasks: [] },
            21: { tasks: [] },
            22: { tasks: [] },
            23: { tasks: [] },
            24: { tasks: [] },
            25: { tasks: [] },
            26: { tasks: [] },
            27: { tasks: [] },
            28: { tasks: [] },
            29: { tasks: [] },
            30: { tasks: [] },
            31: { tasks: [] },
        },
        June: {
            1: { tasks: [] },
            2: { tasks: [] },
            3: { tasks: [] },
            4: { tasks: [] },
            5: { tasks: [] },
            6: { tasks: [] },
            7: { tasks: [] },
            8: { tasks: [] },
            9: { tasks: [] },
            10: { tasks: [] },
            11: { tasks: [] },
            12: { tasks: [] },
            13: { tasks: [] },
            14: { tasks: [] },
            15: { tasks: [] },
            16: { tasks: [] },
            17: { tasks: [] },
            18: { tasks: [] },
            19: { tasks: [] },
            20: { tasks: [] },
            21: { tasks: [] },
            22: { tasks: [] },
            23: { tasks: [] },
            24: { tasks: [] },
            25: { tasks: [] },
            26: { tasks: [] },
            27: { tasks: [] },
            28: { tasks: [] },
            29: { tasks: [] },
            30: { tasks: [] },
            31: { tasks: [] },
        },
        July: {
            1: { tasks: [] },
            2: { tasks: [] },
            3: { tasks: [] },
            4: { tasks: [] },
            5: { tasks: [] },
            6: { tasks: [] },
            7: { tasks: [] },
            8: { tasks: [] },
            9: { tasks: [] },
            10: { tasks: [] },
            11: { tasks: [] },
            12: { tasks: [] },
            13: { tasks: [] },
            14: { tasks: [] },
            15: { tasks: [] },
            16: { tasks: [] },
            17: { tasks: [] },
            18: { tasks: [] },
            19: { tasks: [] },
            20: { tasks: [] },
            21: { tasks: [] },
            22: { tasks: [] },
            23: { tasks: [] },
            24: { tasks: [] },
            25: { tasks: [] },
            26: { tasks: [] },
            27: { tasks: [] },
            28: { tasks: [] },
            29: { tasks: [] },
            30: { tasks: [] },
            31: { tasks: [] },
        },
        August: {
            1: { tasks: [] },
            2: { tasks: [] },
            3: { tasks: [] },
            4: { tasks: [] },
            5: { tasks: [] },
            6: { tasks: [] },
            7: { tasks: [] },
            8: { tasks: [] },
            9: { tasks: [] },
            10: { tasks: [] },
            11: { tasks: [] },
            12: { tasks: [] },
            13: { tasks: [] },
            14: { tasks: [] },
            15: { tasks: [] },
            16: { tasks: [] },
            17: { tasks: [] },
            18: { tasks: [] },
            19: { tasks: [] },
            20: { tasks: [] },
            21: { tasks: [] },
            22: { tasks: [] },
            23: { tasks: [] },
            24: { tasks: [] },
            25: { tasks: [] },
            26: { tasks: [] },
            27: { tasks: [] },
            28: { tasks: [] },
            29: { tasks: [] },
            30: { tasks: [] },
            31: { tasks: [] },
        },
        September: {
            1: { tasks: [] },
            2: { tasks: [] },
            3: { tasks: [] },
            4: { tasks: [] },
            5: { tasks: [] },
            6: { tasks: [] },
            7: { tasks: [] },
            8: { tasks: [] },
            9: { tasks: [] },
            10: { tasks: [] },
            11: { tasks: [] },
            12: { tasks: [] },
            13: { tasks: [] },
            14: { tasks: [] },
            15: { tasks: [] },
            16: { tasks: [] },
            17: { tasks: [] },
            18: { tasks: [] },
            19: { tasks: [] },
            20: { tasks: [] },
            21: { tasks: [] },
            22: { tasks: [] },
            23: { tasks: [] },
            24: { tasks: [] },
            25: { tasks: [] },
            26: { tasks: [] },
            27: { tasks: [] },
            28: { tasks: [] },
            29: { tasks: [] },
            30: { tasks: [] },
            31: { tasks: [] },
        },
        October: {
            1: { tasks: [] },
            2: { tasks: [] },
            3: { tasks: [] },
            4: { tasks: [] },
            5: { tasks: [] },
            6: { tasks: [] },
            7: { tasks: [] },
            8: { tasks: [] },
            9: { tasks: [] },
            10: { tasks: [] },
            11: { tasks: [] },
            12: { tasks: [] },
            13: { tasks: [] },
            14: { tasks: [] },
            15: { tasks: [] },
            16: { tasks: [] },
            17: { tasks: [] },
            18: { tasks: [] },
            19: { tasks: [] },
            20: { tasks: [] },
            21: { tasks: [] },
            22: { tasks: [] },
            23: { tasks: [] },
            24: { tasks: [] },
            25: { tasks: [] },
            26: { tasks: [] },
            27: { tasks: [] },
            28: { tasks: [] },
            29: { tasks: [] },
            30: { tasks: [] },
            31: { tasks: [] },
        },
        November: {
            1: { tasks: [] },
            2: { tasks: [] },
            3: { tasks: [] },
            4: { tasks: [] },
            5: { tasks: [] },
            6: { tasks: [] },
            7: { tasks: [] },
            8: { tasks: [] },
            9: { tasks: [] },
            10: { tasks: [] },
            11: { tasks: [] },
            12: { tasks: [] },
            13: { tasks: [] },
            14: { tasks: [] },
            15: { tasks: [] },
            16: { tasks: [] },
            17: { tasks: [] },
            18: { tasks: [] },
            19: { tasks: [] },
            20: { tasks: [] },
            21: { tasks: [] },
            22: { tasks: [] },
            23: { tasks: [] },
            24: { tasks: [] },
            25: { tasks: [] },
            26: { tasks: [] },
            27: { tasks: [] },
            28: { tasks: [] },
            29: { tasks: [] },
            30: { tasks: [] },
            31: { tasks: [] },
        },
        December: {
            1: { tasks: [] },
            2: { tasks: [] },
            3: { tasks: [] },
            4: { tasks: [] },
            5: { tasks: [] },
            6: { tasks: [] },
            7: { tasks: [] },
            8: { tasks: [] },
            9: { tasks: [] },
            10: { tasks: [] },
            11: { tasks: [] },
            12: { tasks: [] },
            13: { tasks: [] },
            14: { tasks: [] },
            15: { tasks: [] },
            16: { tasks: [] },
            17: { tasks: [] },
            18: { tasks: [] },
            19: { tasks: [] },
            20: { tasks: [] },
            21: { tasks: [] },
            22: { tasks: [] },
            23: { tasks: [] },
            24: { tasks: [] },
            25: { tasks: [] },
            26: { tasks: [] },
            27: { tasks: [] },
            28: { tasks: [] },
            29: { tasks: [] },
            30: { tasks: [] },
            31: { tasks: [] },
        }
    }
};


export const taskReducer = (state = InitialState, action) =>{
    switch (action.type) {
        case ADD_TASK:
            const { month, day } = state.currentDay;
            const updatedMonth = { ...state.month };
            const currentDayTasks = updatedMonth[month]?.[day]?.tasks || [];
            const newTasks = [...currentDayTasks, action.payload];
            return {
                ...state,
                month: {
                    ...state.month,
                    [month]: {
                        ...state.month[month],
                        [day]: { tasks: newTasks }
                    }
                }
            };
        case REMOVE_TASK:
            const { month: monthToRemove, day: dayToRemove } = state.currentDay;
            const tasksForDayToRemove = state.month[monthToRemove]?.[dayToRemove]?.tasks || [];
            const indexToRemove = action.payload;
            const updatedTasksForDay = tasksForDayToRemove.filter((task, index) => index !== indexToRemove);
            return {
                ...state,
                month: {
                    ...state.month,
                    [monthToRemove]: {
                        ...state.month[monthToRemove],
                        [dayToRemove]: { tasks: updatedTasksForDay }
                    }
                }
            };
        case COMPLETE_TASK:
            const { month: monthToComplete, day: dayToComplete } = state.currentDay;
            const tasksForDayToComplete = state.month[monthToComplete]?.[dayToComplete]?.tasks || [];
            const indexToComplete = action.payload;
            const updatedTasksForDayToComplete = tasksForDayToComplete.map((task, index) => {
                if (index === indexToComplete) {
                    return { ...task, isCompleted: !task.isCompleted };
                }
                return task;
            });
            return {
                ...state,
                month: {
                    ...state.month,
                    [monthToComplete]: {
                        ...state.month[monthToComplete],
                        [dayToComplete]: { tasks: updatedTasksForDayToComplete }
                    }
                }
            };
            
                
        case SET_CURRENT_DAY:
            return {...state, currentDay: action.payload}
        default:
            return state
    }
}